[General]
Background=/usr/share/sddm/themes/agisota/background.png
ScaleImageCropped=true
ScreenWidth=3456
ScreenHeight=2234

HeaderText=AGISOTA

# Colors
AccentColor=#FF6B35
BackgroundColor=#121216
ForegroundColor=#E8EAEC
DimColor=#A1A9B1

# Font
Font="Victor Mono"
FontSize=13

HaveFormBackground=true
FormPosition=center
PartialBlur=true
BlurRadius=40
